---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths: {}
components:
  securitySchemes:
    BearerToken:
      description: Auth0 bearer token
      scheme: bearer
      type: apiKey
      name: Authorization
      in: header
security:
- BearerToken: []
servers:
- url: http://localhost:3000
- url: https://etuduo-backend.herokuapp.com/
