---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/tasks":
    get:
      summary: list tasks
      responses:
        '200':
          description: successful
    post:
      summary: create task
      responses:
        '200':
          description: successful
  "/tasks/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show task
      responses:
        '200':
          description: successful
    patch:
      summary: update task
      responses:
        '200':
          description: successful
    put:
      summary: update task
      responses:
        '200':
          description: successful
    delete:
      summary: delete task
      responses:
        '200':
          description: successful
  "/user":
    get:
      summary: User infos
      tags:
      - User
      description: Fetch the user's informations stored in the DB
      responses:
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '200':
          description: Successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user"
    post:
      summary: User creation
      tags:
      - User
      description: Create a user in DB to sync with Auth0 user
      parameters: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user"
        '401':
          description: Unauthorized
        '409':
          description: Conflict
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/requestSchemas/createUser"
        description: Create with user infos
    delete:
      summary: User deletion
      tags:
      - User
      description: Delete the user in DB to desync with Auth0 user
      responses:
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '204':
          description: Deleted
    put:
      summary: User update
      tags:
      - User
      description: Update the user's infos in DB
      parameters: []
      responses:
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '200':
          description: Successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/requestSchemas/updateUser"
        description: Update with user infos
    patch:
      summary: User update
      tags:
      - User
      description: Update the user's infos in DB
      parameters: []
      responses:
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '200':
          description: Successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/requestSchemas/updateUser"
        description: Update with user infos
components:
  securitySchemes:
    BearerToken:
      description: Auth0 bearer token
      scheme: bearer
      type: apiKey
      name: Authorization
      in: header
  schemas:
    user:
      type: object
      properties:
        auth0Id:
          type: string
        username:
          type: string
      required:
      - auth0Id
      - username
  responseSchemas: {}
  requestSchemas:
    createUser:
      properties:
        username:
          type: string
      required:
      - username
    updateUser:
      properties:
        username:
          type: string
security:
- BearerToken: []
servers:
- url: http://localhost:3000
- url: https://etuduo-backend.herokuapp.com/
