---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/tasks":
    get:
      summary: list tasks
      tags:
      - Tasks
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/task"
        '401':
          description: Unauthorized
    post:
      summary: create task
      tags:
      - Tasks
      parameters: []
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/task"
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              allOf:
              - "$ref": "#/components/propertiesSchemas/taskProperties"
              required:
              - title
              - description
              - done
        description: Task infos
  "/tasks/{id}":
    parameters:
    - name: id
      in: path
      description: DB object id
      required: true
      schema:
        type: integer
    get:
      summary: show task
      tags:
      - Tasks
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/task"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      summary: delete task
      tags:
      - Tasks
      responses:
        '204':
          description: Deleted
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    patch:
      summary: update task
      tags:
      - Tasks
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/task"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/propertiesSchemas/taskProperties"
        description: Task infos
    put:
      summary: update task
      tags:
      - Tasks
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/task"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/propertiesSchemas/taskProperties"
        description: Task infos
  "/user":
    get:
      summary: User infos
      tags:
      - User
      description: Fetch the user's informations stored in the DB
      responses:
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '200':
          description: Successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user"
    post:
      summary: User creation
      tags:
      - User
      description: Create a user in DB to sync with Auth0 user
      parameters: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user"
        '401':
          description: Unauthorized
        '409':
          description: Conflict
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/requestSchemas/createUser"
        description: Create with user infos
    delete:
      summary: User deletion
      tags:
      - User
      description: Delete the user in DB to desync with Auth0 user
      responses:
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '204':
          description: Deleted
    put:
      summary: User update
      tags:
      - User
      description: Update the user's infos in DB
      parameters: []
      responses:
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '200':
          description: Successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/requestSchemas/updateUser"
        description: Update with user infos
    patch:
      summary: User update
      tags:
      - User
      description: Update the user's infos in DB
      parameters: []
      responses:
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '200':
          description: Successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/requestSchemas/updateUser"
        description: Update with user infos
components:
  securitySchemes:
    BearerToken:
      description: Auth0 bearer token
      scheme: bearer
      type: apiKey
      name: Authorization
      in: header
  schemas:
    user:
      allOf:
      - "$ref": "#/components/idSchemas/withAuth0Id"
      - "$ref": "#/components/propertiesSchemas/userProperties"
      required:
      - auth0Id
      - username
    task:
      allOf:
      - "$ref": "#/components/idSchemas/withId"
      - "$ref": "#/components/propertiesSchemas/taskProperties"
      required:
      - id
      - title
      - description
      - done
      - start
      - end
  idSchemas:
    withAuth0Id:
      type: object
      properties:
        auth0Id:
          type: string
    withId:
      type: object
      properties:
        id:
          type: integer
  propertiesSchemas:
    userProperties:
      type: object
      properties:
        auth0Id:
          type: string
        username:
          type: string
    taskProperties:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        done:
          type: boolean
        start:
          type: string
          format: date-time
          nullable: true
        end:
          type: string
          format: date-time
          nullable: true
  responseSchemas: {}
  requestSchemas:
    createUser:
      properties:
        username:
          type: string
      required:
      - username
    updateUser:
      properties:
        username:
          type: string
security:
- BearerToken: []
servers:
- url: http://localhost:3000
- url: https://etuduo-backend.herokuapp.com/
